name: commons_lang
description: Commons Lang provides a host of helper utilities for Dart / Flutter applications.
version: 0.0.3
repository: https://github.com/Limeslice-Software-Foundation/commons-lang

environment:
  sdk: ^3.4.3

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
